[package]
name = "fifo_hashset"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#coca = "0.3"
heapless = "0.7.9"


